# Generated by Django 4.2.4 on 2023-08-18 23:34

from django.db import migrations


def fill_link_types(apps, schema_editor):
    LinkType = apps.get_model("bookmarks", "LinkType")
    LinkType.objects.create(type='website')
    LinkType.objects.create(type='book')
    LinkType.objects.create(type='article')
    LinkType.objects.create(type='music')
    LinkType.objects.create(type='video')


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_link_types),
    ]
