# Generated by Django 4.2.4 on 2023-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20230819_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
