# Generated by Django 4.2.4 on 2023-08-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link_type',
            field=models.ForeignKey(default='website', on_delete=django.db.models.deletion.SET_DEFAULT, to='bookmarks.linktype'),
        ),
    ]
