version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


volumes:
  postgres_data: